name: Build and Deploy Code

on:
  push:
    branches:
      - "main"

jobs:
  job1:
    env:
      DATABASE_HOSTNAME=localhost
      DATABASE_PORT=5432
      DATABASE_PASSWORD=pw123456789
      DATABASE_NAME=fastapi
      DATABASE_USERNAME=postgres
      SECRET_KEY=8dfbc5d1b402724e0aea323e66f5c0484d387d1a97f86f0725dac506c5052f57
      ALGORITHM=HS256
      ACCESS_TOKEN_EXPIRE_MINUTES=60
    runs-on: windows-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v7
      - name: Install python version 3.13
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run:  |
          pip install pytest
          pytest